[book]
authors = ["Ace Eldeib"]
language = "en"
multilingual = false
src = "markdown"
title = "Ace's Personal Docs"

[build]
build-dir = "docs"
create-missing = true

[output.html.playpen]
editable = true

[output.html]
theme = "theme"

